### ISSUE TITLE
Wheat Seeds Placed by Scythe not Growing? Minetest 5.3

### ISSUE THREAD

**Issue by FriendlyGamer** [t-affeldt/sickles#2] opened 2020-07-13 18:14 UTC
Literally if it placed by the scythe it will not grow but breaking them and placing the same seeds by hand will resume intended behaviors of the seeds (they grows).

**Comment by t-affeldt** [comment] 2020-07-14 17:46
Thank you for the report. I will investigate this issue. Are you using farming_redo or only the farming mod that comes with Minetest Game?

**Comment by FriendlyGamer** [comment] 2020-07-14 18:45
> Thank you for the report. I will investigate this issue. Are you using farming_redo or only the farming mod that comes with Minetest Game?

You are most certainly welcome, the default Farming Mod shipped by the Minetest Game.

**Comment by t-affeldt** [comment] 2020-10-08 11:24
There was indeed a bug in my mod preventing the block timer from getting triggered.
Farming Redo seems to be working fine. It should also work with the normal farming mod as intended now.
You will have to replace already existing crops, though.

Fixed as of https://github.com/t-affeldt/sickles/commit/64f88263e223c0eb22a0721cda0e9680c65f5267

**Closed as completed** 2020-10-08 11:24 UTC
Labels: bug
